### ISSUE TITLE
Article itself is included in the link

### ISSUE THREAD

**Issue by ferenci-tamas** [dmurdoch/magyarbookdown#2]
It is a very minor issue, but if we want to be consistent with LaTeX, the definite article itself shouldn't be part of the link itself (i.e. `az <a>1.1</a>`).

**Comment by dmurdoch** [comment]
Should be fixed now.

**Comment by ferenci-tamas** [comment]
Thank you very much, works perfectly! (Side note: I don't anything about the policy of the authors of the `bookdown` package in that respect, but it'd be nice if this would be included in the package itself at some point!)

**Comment by dmurdoch** [comment]
I have submitted a pull request to that project (see https://github.com/rstudio/bookdown/pull/672).  I don't know what their response will be, but in the short term, you can try this out using `install_github("dmurdoch/bookdown")`.  It is intended to perform the same as `magyarbookdown`; if you notice any differences, please let me know.

**Comment by ferenci-tamas** [comment]
I've read [your question](https://github.com/rstudio/bookdown/issues/671), thank you very much, I'll be really interested in their answer...
